name: e2e

on: push
#  push:
#    branches:
#      - master

jobs:
  test:
    name: Test
    runs-on: macos-latest

    strategy:
      matrix:
        config: ['ios.sim']
        nativescript: ['6.5.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Python
        uses: actions/setup-python@v1

      - name: Install Detox
        run: |
          brew tap wix/brew
          brew install applesimutils
          npm i -g detox-cli

      - name: Install NativeScript
        run: |
          python -m pip install --upgrade pip six
          npm i -g nativescript@${{ matrix.nativescript }} --ignore-scripts
          tns usage-reporting disable
          tns error-reporting disable
          tns doctor

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: detox build -c ${{ matrix.config }}

      - name: Create Emulator
        if: matrix.config == 'android.emu'
        run: |
          echo no | $ANDROID_HOME/tools/bin/avdmanager \
          create avd \
          --force \
          -n Pixel_3_XL_API_29 \
          --package "system-images;android-29;"

      - name: Test
        run: detox test -c ${{ matrix.config }} --take-screenshots failing --artifacts-location ./.artifacts/ --cleanup

      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.config }}-artifacts
          path: ./.artifacts
